name: Java CI with Maven and SCP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build-The-Project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: List Target Directory Content
        run: cd target && ls -all

  Transfer-To-EC2:
    runs-on: ubuntu-latest
    needs: Build-The-Project

    steps:
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/temporary_private_key
          chmod 600 ~/.ssh/temporary_private_key

      - name: List Target Directory Content on EC2 Before Copy
        run: ssh -i ~/.ssh/temporary_private_key -p 22 -o StrictHostKeyChecking=no ubuntu@15.206.0.236 'ls -all /devopsTest/'

      - name: Copy JAR to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/temporary_private_key -P 22 target/SprinngBootDevopsTest-0.0.1-SNAPSHOT.jar ubuntu@15.206.0.236:/devopsTest/

      - name: List Target Directory Content on EC2 After Copy
        run: ssh -i ~/.ssh/temporary_private_key -p 22 ubuntu@15.206.0.236 'ls -all /devopsTest/'
